/** @type {import('tailwindcss').Config} */
export default {
  // content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],

  darkMode: "class",
  theme: {
    extend: {
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
        "bounce-in": "bounceIn 0.6s ease-out forwards",
        "slide-in-left": "slideInLeft 0.5s ease-out forwards",
        "bounce-subtle": "bounceSubtle 2s ease-in-out infinite",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "gradient-x": "gradientX 3s ease infinite",
        shimmer: "shimmer 2s ease-in-out infinite",
        "spin-slow": "spin 20s linear infinite",
        "count-up": "countUp 2s ease-out forwards",
        "float-1": "float1 10s ease-in-out infinite",
        "float-2": "float2 12s ease-in-out infinite",
        "float-3": "float3 11s ease-in-out infinite",
        "float-4": "float4 9s ease-in-out infinite",
        "pop-in": "pop-in 0.6s ease-out forwards",
        "slide-up": "slide-up 0.6s ease-out forwards",
        "rotate-in": "rotate-in 0.8s ease-out forwards",
        "pulse-scale": "pulse-scale 1.5s ease-in-out infinite",
        "background-pan": "background-pan 10s linear infinite",
        "text-gradient-animation": "text-gradient-animation 3s ease infinite",
        "border-pulse": "border-pulse 2s ease-in-out infinite",
        shine: "shine 1.5s infinite linear",
        glow: "glow 1.5s ease-in-out infinite",
        wave: "wave 1.5s ease-in-out infinite",
        float: "float 3s ease-in-out infinite",
        "scale-up": "scale-up 0.5s ease-out forwards",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "slide-in-right": "slide-in-right 0.6s ease-out forwards",
        "expand-width": "expand-width 0.6s ease-out forwards",
        "fill-color": "fill-color 0.5s ease-out forwards",
        "rotate-y": "rotate-y 1s ease-in-out infinite",
        "flip-in": "flip-in 0.8s ease-out forwards",
        "slide-down": "slide-down 0.6s ease-out forwards",
        "pulse-opacity": "pulse-opacity 1.5s ease-in-out infinite",
        "border-grow": "border-grow 0.6s ease-out forwards",
        "background-fade": "background-fade 0.8s ease-out forwards",
        "text-pop-up": "text-pop-up 0.6s ease-out forwards",
        "icon-bounce": "icon-bounce 1s ease-in-out infinite",
        "shadow-pulse": "shadow-pulse 2s ease-in-out infinite",
        "background-slide": "background-slide 10s linear infinite",
        "color-change": "color-change 2s ease-in-out infinite",
        "border-spin": "border-spin 2s linear infinite",
        "pulse-border": "pulse-border 2s ease-in-out infinite",
        "background-gradient-shift":
          "background-gradient-shift 3s ease infinite",
        "text-glow": "text-glow 2s ease-in-out infinite",
        "scale-bounce": "scale-bounce 1.5s ease-in-out infinite",
        "slide-in-up-stagger": "slide-in-up-stagger 0.8s ease-out forwards",
        "fade-in-down": "fade-in-down 0.6s ease-out forwards",
        "slide-in-left-stagger": "slide-in-left-stagger 0.8s ease-out forwards",
        "rotate-y-hover": "rotate-y-hover 0.5s ease-in-out forwards",
        "pulse-shadow": "pulse-shadow 2s ease-in-out infinite",
        "background-pulse": "background-pulse 2s ease-in-out infinite",
        "border-flash": "border-flash 1.5s ease-in-out infinite",
        "text-slide-in": "text-slide-in 0.8s ease-out forwards",
        "icon-pop": "icon-pop 0.6s ease-out forwards",
        "card-flip": "card-flip 1s ease-in-out forwards",
        "background-pan-light": "background-pan-light 10s linear infinite",
        "background-pan-dark": "background-pan-dark 10s linear infinite",
        "gradient-flow": "gradient-flow 3s ease infinite",
        "pulse-ring": "pulse-ring 2s ease-out infinite",
        "slide-in-from-bottom": "slide-in-from-bottom 0.6s ease-out forwards",
        "slide-in-from-top": "slide-in-from-top 0.6s ease-out forwards",
        "fade-zoom-in": "fade-zoom-in 0.8s ease-out forwards",
        "rotate-scale-up": "rotate-scale-up 1s ease-in-out forwards",
        "bounce-y": "bounce-y 1.5s ease-in-out infinite",
        swing: "swing 1s ease-in-out infinite",
        wobble: "wobble 1s ease-in-out infinite",
        jello: "jello 1s ease-in-out infinite",
        rubberBand: "rubberBand 1s ease-in-out infinite",
        headShake: "headShake 1s ease-in-out infinite",
        "pulse-light": "pulse-light 2s ease-in-out infinite",
        "pulse-dark": "pulse-dark 2s ease-in-out infinite",
        "fade-in-left": "fade-in-left 0.6s ease-out forwards",
        "fade-in-right": "fade-in-right 0.6s ease-out forwards",
        "zoom-in": "zoom-in 0.6s ease-out forwards",
        "slide-in-up": "slide-in-up 0.6s ease-out forwards",
        "slide-in-down": "slide-in-down 0.6s ease-out forwards",
        "rotate-in-center": "rotate-in-center 0.8s ease-out forwards",
        "flip-horizontal-bottom":
          "flip-horizontal-bottom 0.8s ease-out forwards",
        "swing-in-top-fwd": "swing-in-top-fwd 0.8s ease-out forwards",
        "slide-in-elliptic-top-fwd":
          "slide-in-elliptic-top-fwd 0.8s ease-out forwards",
        "scale-in-center": "scale-in-center 0.8s ease-out forwards",
        "focus-in-contract": "focus-in-contract 0.8s ease-out forwards",
        "tracking-in-expand": "tracking-in-expand 0.8s ease-out forwards",
        "tracking-out-contract": "tracking-out-contract 0.8s ease-out forwards",
        "puff-in-center": "puff-in-center 0.8s ease-out forwards",
        "slide-in-blurred-top": "slide-in-blurred-top 0.8s ease-out forwards",
        "slide-in-fwd-center": "slide-in-fwd-center 0.8s ease-out forwards",
        "slide-in-fwd-top": "slide-in-fwd-top 0.8s ease-out forwards",
        "slide-in-fwd-bottom": "slide-in-fwd-bottom 0.8s ease-out forwards",
        "slide-in-fwd-left": "slide-in-fwd-left 0.8s ease-out forwards",
        "slide-in-fwd-right": "slide-in-fwd-right 0.8s ease-out forwards",
        "rotate-in-2-cw": "rotate-in-2-cw 0.8s ease-out forwards",
        "rotate-in-2-ccw": "rotate-in-2-ccw 0.8s ease-out forwards",
        "rotate-in-2-bl": "rotate-in-2-bl 0.8s ease-out forwards",
        "rotate-in-2-br": "rotate-in-2-br 0.8s ease-out forwards",
        "rotate-in-2-tl": "rotate-in-2-tl 0.8s ease-out forwards",
        "rotate-in-2-tr": "rotate-in-2-tr 0.8s ease-out forwards",
        "rotate-in-2-t-cw": "rotate-in-2-t-cw 0.8s ease-out forwards",
        "rotate-in-2-t-ccw": "rotate-in-2-t-ccw 0.8s ease-out forwards",
        "rotate-in-2-b-cw": "rotate-in-2-b-cw 0.8s ease-out forwards",
        "rotate-in-2-b-ccw": "rotate-in-2-b-ccw 0.8s ease-out forwards",
        "rotate-in-2-l-cw": "rotate-in-2-l-cw 0.8s ease-out forwards",
        "rotate-in-2-l-ccw": "rotate-in-2-l-ccw 0.8s ease-out forwards",
        "rotate-in-2-r-cw": "rotate-in-2-r-cw 0.8s ease-out forwards",
        "rotate-in-2-r-ccw": "rotate-in-2-r-ccw 0.8s ease-out forwards",
        "rotate-in-2-fwd-center":
          "rotate-in-2-fwd-center 0.8s ease-out forwards",
        "rotate-in-2-fwd-top": "rotate-in-2-fwd-top 0.8s ease-out forwards",
        "rotate-in-2-fwd-bottom":
          "rotate-in-2-fwd-bottom 0.8s ease-out forwards",
        "rotate-in-2-fwd-left": "rotate-in-2-fwd-left 0.8s ease-out forwards",
        "rotate-in-2-fwd-right": "rotate-in-2-fwd-right 0.8s ease-out forwards",
        "rotate-in-2-bck-center":
          "rotate-in-2-bck-center 0.8s ease-out forwards",
        "rotate-in-2-bck-top": "rotate-in-2-bck-top 0.8s ease-out forwards",
        "rotate-in-2-bck-bottom":
          "rotate-in-2-bck-bottom 0.8s ease-out forwards",
        "rotate-in-2-bck-left": "rotate-in-2-bck-left 0.8s ease-out forwards",
        "rotate-in-2-bck-right": "rotate-in-2-bck-right 0.8s ease-out forwards",
        "rotate-in-2-cw-top": "rotate-in-2-cw-top 0.8s ease-out forwards",
        "rotate-in-2-ccw-top": "rotate-in-2-ccw-top 0.8s ease-out forwards",
        "rotate-in-2-cw-bottom": "rotate-in-2-cw-bottom 0.8s ease-out forwards",
        "rotate-in-2-ccw-bottom":
          "rotate-in-2-ccw-bottom 0.8s ease-out forwards",
        "rotate-in-2-cw-left": "rotate-in-2-cw-left 0.8s ease-out forwards",
        "rotate-in-2-ccw-left": "rotate-in-2-ccw-left 0.8s ease-out forwards",
        "rotate-in-2-cw-right": "rotate-in-2-cw-right 0.8s ease-out forwards",
        "rotate-in-2-ccw-right": "rotate-in-2-ccw-right 0.8s ease-out forwards",
        "rotate-in-2-cw-bl": "rotate-in-2-cw-bl 0.8s ease-out forwards",
        "rotate-in-2-ccw-bl": "rotate-in-2-ccw-bl 0.8s ease-out forwards",
        "rotate-in-2-cw-br": "rotate-in-2-cw-br 0.8s ease-out forwards",
        "rotate-in-2-ccw-br": "rotate-in-2-ccw-br 0.8s ease-out forwards",
        "rotate-in-2-cw-tl": "rotate-in-2-cw-tl 0.8s ease-out forwards",
        "rotate-in-2-ccw-tl": "rotate-in-2-ccw-tl 0.8s ease-out forwards",
        "rotate-in-2-cw-tr": "rotate-in-2-cw-tr 0.8s ease-out forwards",
        "rotate-in-2-ccw-tr": "rotate-in-2-ccw-tr 0.8s ease-out forwards",
        "rotate-in-2-fwd-bl": "rotate-in-2-fwd-bl 0.8s ease-out forwards",
        "rotate-in-2-fwd-br": "rotate-in-2-fwd-br 0.8s ease-out forwards",
        "rotate-in-2-fwd-tl": "rotate-in-2-fwd-tl 0.8s ease-out forwards",
        "rotate-in-2-fwd-tr": "rotate-in-2-fwd-tr 0.8s ease-out forwards",
        "rotate-in-2-bck-bl": "rotate-in-2-bck-bl 0.8s ease-out forwards",
        "rotate-in-2-bck-br": "rotate-in-2-bck-br 0.8s ease-out forwards",
        "rotate-in-2-bck-tl": "rotate-in-2-bck-tl 0.8s ease-out forwards",
        "rotate-in-2-bck-tr": "rotate-in-2-bck-tr 0.8s ease-out forwards",
        "rotate-in-2-cw-center": "rotate-in-2-cw-center 0.8s ease-out forwards",
        "rotate-in-2-ccw-center":
          "rotate-in-2-ccw-center 0.8s ease-out forwards",
        "rotate-in-2-cw-top-left":
          "rotate-in-2-cw-top-left 0.8s ease-out forwards",
        "rotate-in-2-ccw-top-left":
          "rotate-in-2-ccw-top-left 0.8s ease-out forwards",
        "rotate-in-2-cw-top-right":
          "rotate-in-2-cw-top-right 0.8s ease-out forwards",
        "rotate-in-2-ccw-top-right":
          "rotate-in-2-ccw-top-right 0.8s ease-out forwards",
        "rotate-in-2-cw-bottom-left":
          "rotate-in-2-cw-bottom-left 0.8s ease-out forwards",
        "rotate-in-2-ccw-bottom-left":
          "rotate-in-2-ccw-bottom-left 0.8s ease-out forwards",
        "rotate-in-2-cw-bottom-right":
          "rotate-in-2-cw-bottom-right 0.8s ease-out forwards",
        "rotate-in-2-ccw-bottom-right":
          "rotate-in-2-ccw-bottom-right 0.8s ease-out forwards",
        "rotate-in-2-cw-top-center":
          "rotate-in-2-cw-top-center 0.8s ease-out forwards",
        "rotate-in-2-ccw-top-center":
          "rotate-in-2-ccw-top-center 0.8s ease-out forwards",
        "rotate-in-2-cw-bottom-center":
          "rotate-in-2-cw-bottom-center 0.8s ease-out forwards",
        "rotate-in-2-ccw-bottom-center":
          "rotate-in-2-ccw-bottom-center 0.8s ease-out forwards",
        "rotate-in-2-cw-left-center":
          "rotate-in-2-cw-left-center 0.8s ease-out forwards",
        "rotate-in-2-ccw-left-center":
          "rotate-in-2-ccw-left-center 0.8s ease-out forwards",
        "rotate-in-2-cw-right-center":
          "rotate-in-2-cw-right-center 0.8s ease-out forwards",
        "rotate-in-2-ccw-right-center":
          "rotate-in-2-ccw-right-center 0.8s ease-out forwards",
        "rotate-in-2-fwd-top-left":
          "rotate-in-2-fwd-top-left 0.8s ease-out forwards",
        "rotate-in-2-fwd-top-right":
          "rotate-in-2-fwd-top-right 0.8s ease-out forwards",
        "rotate-in-2-fwd-bottom-left":
          "rotate-in-2-fwd-bottom-left 0.8s ease-out forwards",
        "rotate-in-2-fwd-bottom-right":
          "rotate-in-2-fwd-bottom-right 0.8s ease-out forwards",
        "rotate-in-2-bck-top-left":
          "rotate-in-2-bck-top-left 0.8s ease-out forwards",
        "rotate-in-2-bck-top-right":
          "rotate-in-2-bck-top-right 0.8s ease-out forwards",
        "rotate-in-2-bck-bottom-left":
          "rotate-in-2-bck-bottom-left 0.8s ease-out forwards",
        "rotate-in-2-bck-bottom-right":
          "rotate-in-2-bck-bottom-right 0.8s ease-out forwards",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
      colors: {
        primary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        secondary: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
        },
        neutral: {
          50: "#f9fafb",
          100: "#f3f4f6",
          200: "#e5e7eb",
          300: "#d1d5db",
          400: "#9ca3af",
          500: "#6b7280",
          600: "#4b5563",
          700: "#374151",
          800: "#1f2937",
          900: "#111827",
        },
      },
    },

  },
  plugins: [],
};
